pub const MIDI_CC_VOLUME: u8 = 7;
pub const MIDI_CC_PAN: u8 = 10;
pub const MIDI_CC_MIN: u8 = 0;
pub const MIDI_CC_MAX: u8 = 127;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InstrumentKind {
    AcousticPiano,
    BrightAcousticPiano,
    ElectricGrandPiano,
    HonkyTonkPiano,
    ElectricPiano1,
    ElectricPiano2,
    Harpsichord,
    Clavinet,

    Celesta,
    Glockenspiel,
    MusicBox,
    Vibraphone,
    Marimba,
    Xylophone,
    TubularBells,
    Dulcimer,

    HammondOrgan,
    PercussiveOrgan,
    RockOrgan,
    ChurchOrgan,
    ReedOrgan,
    Accordion,
    Harmonica,
    Bandoneon,

    AcousticGuitarNylon,
    AcousticGuitarSteel,
    ElectricGuitarJazz,
    ElectricGuitarClean,
    ElectricGuitarMuted,
    OverdrivenGuitar,
    DistortionGuitar,
    GuitarHarmonics,

    AcousticBass,
    ElectricBassFinger,
    ElectricBassPick,
    FretlessBass,
    SlapBass1,
    SlapBass2,
    SynthBass1,
    SynthBass2,

    Violin,
    Viola,
    Cello,
    Contrabass,
    TremoloStrings,
    PizzicatoStrings,
    OrchestralHarp,
    Timpani,

    StringEnsemble1,
    StringEnsemble2,
    SynthStrings1,
    SynthStrings2,
    ChoirAahs,
    VoiceOohs,
    SynthChoir,
    OrchestraHit,

    Trumpet,
    Trombone,
    Tuba,
    MutedTrumpet,
    FrenchHorn,
    BrassSection,
    SynthBrass1,
    SynthBrass2,

    SopranoSax,
    AltoSax,
    TenorSax,
    BaritoneSax,
    Oboe,
    EnglishHorn,
    Bassoon,
    Clarinet,

    Piccolo,
    Flute,
    Recorder,
    PanFlute,
    BlownBottle,
    Shakuhachi,
    Whistle,
    Ocarina,

    Lead1Square,
    Lead2Sawtooth,
    Lead3Calliope,
    Lead4Chiff,
    Lead5Charang,
    Lead6Voice,
    Lead7Fifths,
    Lead8BassLead,

    Pad1NewAge,
    Pad2Warm,
    Pad3Polysynth,
    Pad4Choir,
    Pad5Bowed,
    Pad6Metallic,
    Pad7Halo,
    Pad8Sweep,

    Fx1Rain,
    Fx2Soundtrack,
    Fx3Crystal,
    Fx4Atmosphere,
    Fx5Brightness,
    Fx6Goblins,
    Fx7Echoes,
    Fx8SciFi,

    Sitar,
    Banjo,
    Shamisen,
    Koto,
    Kalimba,
    BagPipe,
    Fiddle,
    Shanai,

    TinkleBell,
    Agogo,
    SteelDrums,
    Woodblock,
    TaikoDrum,
    MelodicTom,
    SynthDrum,
    ReverseCymbal,

    GuitarFretNoise,
    BreathNoise,
    Seashore,
    BirdTweet,
    TelephoneRing,
    Helicopter,
    Applause,
    Gunshot,
}

impl InstrumentKind {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "piano" => Some(Self::AcousticPiano),
            "bright_piano" => Some(Self::BrightAcousticPiano),
            "electric_grand" => Some(Self::ElectricGrandPiano),
            "honky_tonk" => Some(Self::HonkyTonkPiano),
            "electric_piano" => Some(Self::ElectricPiano1),
            "electric_piano2" => Some(Self::ElectricPiano2),
            "harpsichord" => Some(Self::Harpsichord),
            "clavinet" => Some(Self::Clavinet),

            "celesta" => Some(Self::Celesta),
            "glockenspiel" => Some(Self::Glockenspiel),
            "music_box" => Some(Self::MusicBox),
            "vibraphone" => Some(Self::Vibraphone),
            "marimba" => Some(Self::Marimba),
            "xylophone" => Some(Self::Xylophone),
            "tubular_bells" => Some(Self::TubularBells),
            "dulcimer" => Some(Self::Dulcimer),

            "hammond" => Some(Self::HammondOrgan),
            "percussive_organ" => Some(Self::PercussiveOrgan),
            "rock_organ" => Some(Self::RockOrgan),
            "church_organ" => Some(Self::ChurchOrgan),
            "reed_organ" => Some(Self::ReedOrgan),
            "accordion" => Some(Self::Accordion),
            "harmonica" => Some(Self::Harmonica),
            "bandoneon" => Some(Self::Bandoneon),

            "guitar" => Some(Self::AcousticGuitarSteel),
            "guitar_nylon" => Some(Self::AcousticGuitarNylon),
            "guitar_jazz" => Some(Self::ElectricGuitarJazz),
            "guitar_clean" => Some(Self::ElectricGuitarClean),
            "guitar_muted" => Some(Self::ElectricGuitarMuted),
            "overdrive" => Some(Self::OverdrivenGuitar),
            "distortion" => Some(Self::DistortionGuitar),
            "guitar_harmonics" => Some(Self::GuitarHarmonics),

            "bass" => Some(Self::AcousticBass),
            "bass_finger" => Some(Self::ElectricBassFinger),
            "bass_pick" => Some(Self::ElectricBassPick),
            "fretless_bass" => Some(Self::FretlessBass),
            "slap_bass" => Some(Self::SlapBass1),
            "slap_bass2" => Some(Self::SlapBass2),
            "synth_bass" => Some(Self::SynthBass1),
            "synth_bass2" => Some(Self::SynthBass2),

            "violin" => Some(Self::Violin),
            "viola" => Some(Self::Viola),
            "cello" => Some(Self::Cello),
            "contrabass" => Some(Self::Contrabass),
            "tremolo_strings" => Some(Self::TremoloStrings),
            "pizzicato" => Some(Self::PizzicatoStrings),
            "harp" => Some(Self::OrchestralHarp),
            "timpani" => Some(Self::Timpani),

            "strings" => Some(Self::StringEnsemble1),
            "strings2" => Some(Self::StringEnsemble2),
            "synth_strings" => Some(Self::SynthStrings1),
            "synth_strings2" => Some(Self::SynthStrings2),
            "choir" => Some(Self::ChoirAahs),
            "voice" => Some(Self::VoiceOohs),
            "synth_choir" => Some(Self::SynthChoir),
            "orchestra_hit" => Some(Self::OrchestraHit),

            "trumpet" => Some(Self::Trumpet),
            "trombone" => Some(Self::Trombone),
            "tuba" => Some(Self::Tuba),
            "muted_trumpet" => Some(Self::MutedTrumpet),
            "french_horn" => Some(Self::FrenchHorn),
            "brass" => Some(Self::BrassSection),
            "synth_brass" => Some(Self::SynthBrass1),
            "synth_brass2" => Some(Self::SynthBrass2),

            "soprano_sax" => Some(Self::SopranoSax),
            "alto_sax" => Some(Self::AltoSax),
            "tenor_sax" => Some(Self::TenorSax),
            "baritone_sax" => Some(Self::BaritoneSax),
            "oboe" => Some(Self::Oboe),
            "english_horn" => Some(Self::EnglishHorn),
            "bassoon" => Some(Self::Bassoon),
            "clarinet" => Some(Self::Clarinet),

            "piccolo" => Some(Self::Piccolo),
            "flute" => Some(Self::Flute),
            "recorder" => Some(Self::Recorder),
            "pan_flute" => Some(Self::PanFlute),
            "blown_bottle" => Some(Self::BlownBottle),
            "shakuhachi" => Some(Self::Shakuhachi),
            "whistle" => Some(Self::Whistle),
            "ocarina" => Some(Self::Ocarina),

            "lead_square" => Some(Self::Lead1Square),
            "lead_sawtooth" => Some(Self::Lead2Sawtooth),
            "lead_calliope" => Some(Self::Lead3Calliope),
            "lead_chiff" => Some(Self::Lead4Chiff),
            "lead_charang" => Some(Self::Lead5Charang),
            "lead_voice" => Some(Self::Lead6Voice),
            "lead_fifths" => Some(Self::Lead7Fifths),
            "lead_bass" => Some(Self::Lead8BassLead),

            "pad_new_age" => Some(Self::Pad1NewAge),
            "pad_warm" => Some(Self::Pad2Warm),
            "pad_polysynth" => Some(Self::Pad3Polysynth),
            "pad_choir" => Some(Self::Pad4Choir),
            "pad_bowed" => Some(Self::Pad5Bowed),
            "pad_metallic" => Some(Self::Pad6Metallic),
            "pad_halo" => Some(Self::Pad7Halo),
            "pad_sweep" => Some(Self::Pad8Sweep),

            "fx_rain" => Some(Self::Fx1Rain),
            "fx_soundtrack" => Some(Self::Fx2Soundtrack),
            "fx_crystal" => Some(Self::Fx3Crystal),
            "fx_atmosphere" => Some(Self::Fx4Atmosphere),
            "fx_brightness" => Some(Self::Fx5Brightness),
            "fx_goblins" => Some(Self::Fx6Goblins),
            "fx_echoes" => Some(Self::Fx7Echoes),
            "fx_scifi" => Some(Self::Fx8SciFi),

            "sitar" => Some(Self::Sitar),
            "banjo" => Some(Self::Banjo),
            "shamisen" => Some(Self::Shamisen),
            "koto" => Some(Self::Koto),
            "kalimba" => Some(Self::Kalimba),
            "bagpipe" => Some(Self::BagPipe),
            "fiddle" => Some(Self::Fiddle),
            "shanai" => Some(Self::Shanai),

            "tinkle_bell" => Some(Self::TinkleBell),
            "agogo" => Some(Self::Agogo),
            "steel_drums" => Some(Self::SteelDrums),
            "woodblock" => Some(Self::Woodblock),
            "taiko" => Some(Self::TaikoDrum),
            "melodic_tom" => Some(Self::MelodicTom),
            "synth_drum" => Some(Self::SynthDrum),
            "reverse_cymbal" => Some(Self::ReverseCymbal),

            "guitar_fret_noise" => Some(Self::GuitarFretNoise),
            "breath_noise" => Some(Self::BreathNoise),
            "seashore" => Some(Self::Seashore),
            "bird_tweet" => Some(Self::BirdTweet),
            "telephone" => Some(Self::TelephoneRing),
            "helicopter" => Some(Self::Helicopter),
            "applause" => Some(Self::Applause),
            "gunshot" => Some(Self::Gunshot),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::AcousticPiano => "piano",
            Self::BrightAcousticPiano => "bright_piano",
            Self::ElectricGrandPiano => "electric_grand",
            Self::HonkyTonkPiano => "honky_tonk",
            Self::ElectricPiano1 => "electric_piano",
            Self::ElectricPiano2 => "electric_piano2",
            Self::Harpsichord => "harpsichord",
            Self::Clavinet => "clavinet",

            Self::Celesta => "celesta",
            Self::Glockenspiel => "glockenspiel",
            Self::MusicBox => "music_box",
            Self::Vibraphone => "vibraphone",
            Self::Marimba => "marimba",
            Self::Xylophone => "xylophone",
            Self::TubularBells => "tubular_bells",
            Self::Dulcimer => "dulcimer",

            Self::HammondOrgan => "hammond",
            Self::PercussiveOrgan => "percussive_organ",
            Self::RockOrgan => "rock_organ",
            Self::ChurchOrgan => "church_organ",
            Self::ReedOrgan => "reed_organ",
            Self::Accordion => "accordion",
            Self::Harmonica => "harmonica",
            Self::Bandoneon => "bandoneon",

            Self::AcousticGuitarNylon => "guitar_nylon",
            Self::AcousticGuitarSteel => "guitar",
            Self::ElectricGuitarJazz => "guitar_jazz",
            Self::ElectricGuitarClean => "guitar_clean",
            Self::ElectricGuitarMuted => "guitar_muted",
            Self::OverdrivenGuitar => "overdrive",
            Self::DistortionGuitar => "distortion",
            Self::GuitarHarmonics => "guitar_harmonics",

            Self::AcousticBass => "bass",
            Self::ElectricBassFinger => "bass_finger",
            Self::ElectricBassPick => "bass_pick",
            Self::FretlessBass => "fretless_bass",
            Self::SlapBass1 => "slap_bass",
            Self::SlapBass2 => "slap_bass2",
            Self::SynthBass1 => "synth_bass",
            Self::SynthBass2 => "synth_bass2",

            Self::Violin => "violin",
            Self::Viola => "viola",
            Self::Cello => "cello",
            Self::Contrabass => "contrabass",
            Self::TremoloStrings => "tremolo_strings",
            Self::PizzicatoStrings => "pizzicato",
            Self::OrchestralHarp => "harp",
            Self::Timpani => "timpani",

            Self::StringEnsemble1 => "strings",
            Self::StringEnsemble2 => "strings2",
            Self::SynthStrings1 => "synth_strings",
            Self::SynthStrings2 => "synth_strings2",
            Self::ChoirAahs => "choir",
            Self::VoiceOohs => "voice",
            Self::SynthChoir => "synth_choir",
            Self::OrchestraHit => "orchestra_hit",

            Self::Trumpet => "trumpet",
            Self::Trombone => "trombone",
            Self::Tuba => "tuba",
            Self::MutedTrumpet => "muted_trumpet",
            Self::FrenchHorn => "french_horn",
            Self::BrassSection => "brass",
            Self::SynthBrass1 => "synth_brass",
            Self::SynthBrass2 => "synth_brass2",

            Self::SopranoSax => "soprano_sax",
            Self::AltoSax => "alto_sax",
            Self::TenorSax => "tenor_sax",
            Self::BaritoneSax => "baritone_sax",
            Self::Oboe => "oboe",
            Self::EnglishHorn => "english_horn",
            Self::Bassoon => "bassoon",
            Self::Clarinet => "clarinet",

            Self::Piccolo => "piccolo",
            Self::Flute => "flute",
            Self::Recorder => "recorder",
            Self::PanFlute => "pan_flute",
            Self::BlownBottle => "blown_bottle",
            Self::Shakuhachi => "shakuhachi",
            Self::Whistle => "whistle",
            Self::Ocarina => "ocarina",

            Self::Lead1Square => "lead_square",
            Self::Lead2Sawtooth => "lead_sawtooth",
            Self::Lead3Calliope => "lead_calliope",
            Self::Lead4Chiff => "lead_chiff",
            Self::Lead5Charang => "lead_charang",
            Self::Lead6Voice => "lead_voice",
            Self::Lead7Fifths => "lead_fifths",
            Self::Lead8BassLead => "lead_bass",

            Self::Pad1NewAge => "pad_new_age",
            Self::Pad2Warm => "pad_warm",
            Self::Pad3Polysynth => "pad_polysynth",
            Self::Pad4Choir => "pad_choir",
            Self::Pad5Bowed => "pad_bowed",
            Self::Pad6Metallic => "pad_metallic",
            Self::Pad7Halo => "pad_halo",
            Self::Pad8Sweep => "pad_sweep",

            Self::Fx1Rain => "fx_rain",
            Self::Fx2Soundtrack => "fx_soundtrack",
            Self::Fx3Crystal => "fx_crystal",
            Self::Fx4Atmosphere => "fx_atmosphere",
            Self::Fx5Brightness => "fx_brightness",
            Self::Fx6Goblins => "fx_goblins",
            Self::Fx7Echoes => "fx_echoes",
            Self::Fx8SciFi => "fx_scifi",

            Self::Sitar => "sitar",
            Self::Banjo => "banjo",
            Self::Shamisen => "shamisen",
            Self::Koto => "koto",
            Self::Kalimba => "kalimba",
            Self::BagPipe => "bagpipe",
            Self::Fiddle => "fiddle",
            Self::Shanai => "shanai",

            Self::TinkleBell => "tinkle_bell",
            Self::Agogo => "agogo",
            Self::SteelDrums => "steel_drums",
            Self::Woodblock => "woodblock",
            Self::TaikoDrum => "taiko",
            Self::MelodicTom => "melodic_tom",
            Self::SynthDrum => "synth_drum",
            Self::ReverseCymbal => "reverse_cymbal",

            Self::GuitarFretNoise => "guitar_fret_noise",
            Self::BreathNoise => "breath_noise",
            Self::Seashore => "seashore",
            Self::BirdTweet => "bird_tweet",
            Self::TelephoneRing => "telephone",
            Self::Helicopter => "helicopter",
            Self::Applause => "applause",
            Self::Gunshot => "gunshot",
        }
    }

    pub fn midi_program(&self) -> u8 {
        match self {
            Self::AcousticPiano => 0,
            Self::BrightAcousticPiano => 1,
            Self::ElectricGrandPiano => 2,
            Self::HonkyTonkPiano => 3,
            Self::ElectricPiano1 => 4,
            Self::ElectricPiano2 => 5,
            Self::Harpsichord => 6,
            Self::Clavinet => 7,

            Self::Celesta => 8,
            Self::Glockenspiel => 9,
            Self::MusicBox => 10,
            Self::Vibraphone => 11,
            Self::Marimba => 12,
            Self::Xylophone => 13,
            Self::TubularBells => 14,
            Self::Dulcimer => 15,

            Self::HammondOrgan => 16,
            Self::PercussiveOrgan => 17,
            Self::RockOrgan => 18,
            Self::ChurchOrgan => 19,
            Self::ReedOrgan => 20,
            Self::Accordion => 21,
            Self::Harmonica => 22,
            Self::Bandoneon => 23,

            Self::AcousticGuitarNylon => 24,
            Self::AcousticGuitarSteel => 25,
            Self::ElectricGuitarJazz => 26,
            Self::ElectricGuitarClean => 27,
            Self::ElectricGuitarMuted => 28,
            Self::OverdrivenGuitar => 29,
            Self::DistortionGuitar => 30,
            Self::GuitarHarmonics => 31,

            Self::AcousticBass => 32,
            Self::ElectricBassFinger => 33,
            Self::ElectricBassPick => 34,
            Self::FretlessBass => 35,
            Self::SlapBass1 => 36,
            Self::SlapBass2 => 37,
            Self::SynthBass1 => 38,
            Self::SynthBass2 => 39,

            Self::Violin => 40,
            Self::Viola => 41,
            Self::Cello => 42,
            Self::Contrabass => 43,
            Self::TremoloStrings => 44,
            Self::PizzicatoStrings => 45,
            Self::OrchestralHarp => 46,
            Self::Timpani => 47,

            Self::StringEnsemble1 => 48,
            Self::StringEnsemble2 => 49,
            Self::SynthStrings1 => 50,
            Self::SynthStrings2 => 51,
            Self::ChoirAahs => 52,
            Self::VoiceOohs => 53,
            Self::SynthChoir => 54,
            Self::OrchestraHit => 55,

            Self::Trumpet => 56,
            Self::Trombone => 57,
            Self::Tuba => 58,
            Self::MutedTrumpet => 59,
            Self::FrenchHorn => 60,
            Self::BrassSection => 61,
            Self::SynthBrass1 => 62,
            Self::SynthBrass2 => 63,

            Self::SopranoSax => 64,
            Self::AltoSax => 65,
            Self::TenorSax => 66,
            Self::BaritoneSax => 67,
            Self::Oboe => 68,
            Self::EnglishHorn => 69,
            Self::Bassoon => 70,
            Self::Clarinet => 71,

            Self::Piccolo => 72,
            Self::Flute => 73,
            Self::Recorder => 74,
            Self::PanFlute => 75,
            Self::BlownBottle => 76,
            Self::Shakuhachi => 77,
            Self::Whistle => 78,
            Self::Ocarina => 79,

            Self::Lead1Square => 80,
            Self::Lead2Sawtooth => 81,
            Self::Lead3Calliope => 82,
            Self::Lead4Chiff => 83,
            Self::Lead5Charang => 84,
            Self::Lead6Voice => 85,
            Self::Lead7Fifths => 86,
            Self::Lead8BassLead => 87,

            Self::Pad1NewAge => 88,
            Self::Pad2Warm => 89,
            Self::Pad3Polysynth => 90,
            Self::Pad4Choir => 91,
            Self::Pad5Bowed => 92,
            Self::Pad6Metallic => 93,
            Self::Pad7Halo => 94,
            Self::Pad8Sweep => 95,

            Self::Fx1Rain => 96,
            Self::Fx2Soundtrack => 97,
            Self::Fx3Crystal => 98,
            Self::Fx4Atmosphere => 99,
            Self::Fx5Brightness => 100,
            Self::Fx6Goblins => 101,
            Self::Fx7Echoes => 102,
            Self::Fx8SciFi => 103,

            Self::Sitar => 104,
            Self::Banjo => 105,
            Self::Shamisen => 106,
            Self::Koto => 107,
            Self::Kalimba => 108,
            Self::BagPipe => 109,
            Self::Fiddle => 110,
            Self::Shanai => 111,

            Self::TinkleBell => 112,
            Self::Agogo => 113,
            Self::SteelDrums => 114,
            Self::Woodblock => 115,
            Self::TaikoDrum => 116,
            Self::MelodicTom => 117,
            Self::SynthDrum => 118,
            Self::ReverseCymbal => 119,

            Self::GuitarFretNoise => 120,
            Self::BreathNoise => 121,
            Self::Seashore => 122,
            Self::BirdTweet => 123,
            Self::TelephoneRing => 124,
            Self::Helicopter => 125,
            Self::Applause => 126,
            Self::Gunshot => 127,
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Instrument {
    pub kind: InstrumentKind,
    volume: u8,
    pan: u8,
}

impl Instrument {
    pub fn new(kind: InstrumentKind) -> Self {
        Self {
            kind,
            volume: 100,
            pan: 64,
        }
    }

    pub fn volume(&self) -> u8 {
        self.volume
    }

    pub fn pan(&self) -> u8 {
        self.pan
    }

    pub fn set_volume(&mut self, vol: u8) {
        self.volume = vol.clamp(MIDI_CC_MIN, MIDI_CC_MAX);
    }

    pub fn set_pan(&mut self, pan_val: u8) {
        self.pan = pan_val.clamp(MIDI_CC_MIN, MIDI_CC_MAX);
    }

    pub fn midi_program(&self) -> u8 {
        self.kind.midi_program()
    }

    pub fn midi_cc_volume(&self) -> (u8, u8) {
        (MIDI_CC_VOLUME, self.volume)
    }

    pub fn midi_cc_pan(&self) -> (u8, u8) {
        (MIDI_CC_PAN, self.pan)
    }

    pub fn display(&self) -> String {
        format!("inst({})", self.kind.as_str())
    }
}
